theme: jekyll-theme-minimal
title: Conversations with Event Leaders
google_analytics: UA-141606861-1
description: Conversations with Event Leaders is a podcast where we sit down with event organizers and explore stories from their event planning adventures. The goal of the podcast is to have an entertaining, yet informative conversation that helps inspire listeners to approach events in a new way.
show_downloads: false
podcasthost: Podcast hosted by Radiun Huq.
linkedin: https://www.linkedin.com/in/radiunhuq/
email: radi@mrhuq.com
