theme: jekyll-theme-minimal
title: Conversations with Event Leaders
description: Conversations with Event Leaders is a podcast aimed to sit down with event organizers and explore stories from their event planning adventures. The goal of the podcast is to have an entertaining, yet informative conversation that helps inspire listeners to approach events in a new way.
show_downloads: false
